#server:
#  port: 2008

#和重试机制相关的配置有如下四个：
#spring:
#  cloud:
#    config:
#      retry:
#        # 配置重试次数，默认为6
#        max-attempts: 6
#        # 间隔乘数，默认1.1
#        multiplier: 1.1
#        # 初始重试间隔时间，默认1000ms
#        initial-interval: 1000
#        # 最大间隔时间，默认2000ms
#        max-interval: 2000